_extends: private-global-settings



collaborators:
  # peterjgilbert is the owner of this repository
  - username: peterjgilbert
    permission: admin
  
  # armaniferrante is the owner of this repository
  - username: armaniferrante
    permission: admin
  
  # willscott is the owner of this repository
  - username: willscott
    permission: admin
  